---
title: 'Running MLwiN using mlnscript via the R2MLwiN R package on Apple Silicon Macs '
author: Package Build
date: '2023-09-22'
slug: mlnscript-r2mlwin-apple-silicon
categories:
  - Blog
tags:
  - R
  - MLwiN
subtitle: ''
summary: 'How to run MLwiN on Apple Silicon Macs via R.'
authors: []
#lastmod: '2023-09-15T13:02:36+01:00'
featured: no
draft: no
image:
  caption: ''
  focal_point: 'Centre'
  preview_only: no
projects: []
bibliography: refs.bib
link-citations: true
---

```{r include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  comment = '#>'
)
```

## Introduction

The aim of this post is to get MLwiN running on Apple Silicon Macs in R using the **R2MLwiN** package [@mlwin;@r2mlwin]. This is achieved using the non-graphical version of MLwiN called `mlnscript` (`mlnscript.exe` on Windows) which has an accompanying library `libmln.dylib`.

## Setup steps

* Obtain the `MLN.dmg` installer from the Centre for Multilevel Modelling and then install it, see the relevant download page (depending upon whether you are an academic) on the MLwiN [website](https://www.bristol.ac.uk/cmm/software/mlwin/).
* On macOS it is recommended to install the files into the `/opt/mln/` directory, which you will need to create with Admin permissions, or install to another directory if you don't have Admin permissions.
* Once installed we can check that `mlnscript` and `libmln.dylib` are universal binaries,
  ```{bash}
  lipo -archs /opt/mln/mlnscript
  ```
  ```{bash}
  lipo -archs /opt/mln/libmln.dylib
  ```  
  since both architectures are listed this indicates both files are universal binaries.
* Enable security settings

* And we can check it's running with

  ```{bash}
  /opt/mln/mlnscript --version
  ```

* Now we need to install the **R2MLwiN** package from CRAN.
  ```r
  install.packages("R2MLwiN")
  ```

* For an example we could run one of the demos in the package, which we list with
  ```r
  demo(package = "R2MLwiN")
  ```
  Then run one (output omitted)
  ```r
  library(R2MLwiN)
  # if you did not install mlnscript in /opt/mln , set:
  # options(MLwiN_path = "/path-to/mlnscript")
  demo(UserGuide02)
  ```

## Summary

Despite having *Win* in its name, the core libraries for running MLwiN on other platforms, including macOS for both Intel and Apple Silicon processors and versions of Linux, have been available for sometime and are straightforward to use from R and the R2MLwiN package.

## References
