---
title: "Checking your packages and practicals run throughout the year with GitHub Actions"
author: Package Build
date: '2025-02-22'
slug: checking-packages-and-practicals
categories:
  - Blog
tags:
  - R
  - R Markdown
  - Quarto
  - GitHub
  - GitHub Actions
subtitle:
summary: 
authors: []
lastmod: '2025-02-22T08:00:00+00:00'
featured: no
image:
  caption: ''
  focal_point: 'Center'
  preview_only: no
  alt_text: 'Screenshot of '
projects: []
toc: true
---

## Introduction

Do you have a R package that's just on GitHub? Therefore, unlike when a package is on CRAN checks are not being run on that package on a regular basis unless you run them locally. CRAN follows a rolling release model, so any day one of your packages's dependency packages could be updated - breaking your package!

Or maybe you teach a course that runs once a year and it has some R practical sessions? It can be very frustrating when you come to rerun your practical after a year and find that several R packages have been updated and now you have to work out how to fix things. Of course for this situation we could use [**renv**](https://rstudio.github.io/renv/index.html) to record the packages and their versions. But the issue with this is that your course participants will then need to use **renv** which might lead to a room full of 30 students all having **renv** problems. Alternatively you might install all your packages from a single date, meaning you can restore them using the a snapshot date from the Public Posit Package Manager (now the only snapshot) but you might find your course participants why you use packages that are a year out of date.

My solution to these problems is to regularly run `R CMD check` on your package/run your practical with the latest versions of the required packages. This way you'll hopefully pick up any changes in your dependencies long before the next running of your course.

If I had a server I could suggest setting up a [`cron`](https://linux.die.net/man/8/cron) job to check the package or practical. However, most of us don't have a server. Luckily if your package or practical is in a public GitHub repository then we can run GitHub Actions on it. It turns out GitHub Actions has a [scheduling facility that uses `cron` syntax](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule).

next I'll show how to run R code on a schedule on GitHub Actions for the two cases.

## Checking packages on a schedule

I use the actions and example workflows from the [r-lib/actions](https://github.com/r-lib/actions) repository. For checking a package there are several examples, in the _examples_ directory of that repository, that we can copy then amend. Let's use the [check-full.yaml](https://github.com/r-lib/actions/blob/v2-branch/examples/check-full.yaml) example.

Copy this file into a _.github/workflows_ directory in the repository for your package. Now we need to enable scheduled running. Amend the first `on:` block to include the two lines I have inserted below.

```yaml
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# NOTE: This workflow is overkill for most R packages and
# check-standard.yaml is likely a better choice.
# usethis::use_github_action("check-standard") will install it.
on:
  push:
    branches: [main, master]
  pull_request:
  schedule:
    - cron: "00 9 * * TUE"
```

What does this syntax mean? Luckily there are many websites which will decipher that for us, such as [crontab guru](https://crontab.guru/).

TODO cron-tab-guru-screen

We see this means run a 9:00 am (UTC) on Tuesdays. Once you have committed this file to your repo and pushed it to GitHub on your main/master branch then your automated checking is taken care of.

## Running practicals on a schedule

My opinion is that running the practical once per month is about the sweetspot.

## Summary

I have shown how to use GitHub Actions scheduling feature to automatically run scheduled checks on packages and R scripts/R Markdown/Quarto documents for practicals.
