---
title: "Running the nbstata Jupyter kernel within a uv virtual environment"
author: Package Build
date: '2025-04-29'
slug: nbstata-uv-venv
categories:
  - Blog
tags:
  - GitHub
  - Stata
  - Jupyter
  - nbstata
  - Quarto
subtitle:
summary: "How to setup a uv virtual environment to run the nbstata Jupyter kernel."
authors: []
lastmod: '2025-04-29T07:00:00+00:00'
featured: no
image:
  caption: ''
  focal_point: 'Center'
  preview_only: no
  alt_text: 'Screenshot of ...'
projects: []
toc: true
---

## Introduction

Any new project using Python or Jupyter now needs to use a virtual environment. This is just a directory within your project which will contain the dependency Python packages.

There are many Python project managers, the new and extremly fast project manager is [uv](https://docs.astral.sh/uv/).

In this post I will explain how to use the [nbstata](https://hugetim.github.io/nbstata/) Jupyter kernel within a uv virtual environment on macOS, Windows, and Linux.

I should say at this point that I am a contributor to the excellent [Statamarkdown](https://cran.r-project.org/package=Statamarkdown) R package by Doug Hemken which can also be used in Quarto documents using the knitr engine. But in this post I'll be using nbstata because nbstata uses pystata which is StataCorp's official Python package (included in each Stata installation) and is their official way of integrating Stata in Python. As such pystata and hence nbstata have more features than Statamarkdown can provide.

## Setup basics

On your machine you need to have

* Stata installed and know the location of the installation
  * and check that within the installation their is the utilities directory containing the pystata directory
* uv must be installed, see [its docs for more info](https://docs.astral.sh/uv/getting-started/installation/)
* and of course a text editor and a terminal
* On Windows I would recommend using Git Bash (which is bundled with [Git for Windows](https://git-scm.com/downloads/win)) for running the setup script in the next section.

## A shell script to setup the virtual environment

What follows are the shell commands we need to run to setup our virtual environment.

It's for macOS but I put comments in the places where amendments are required for either Windows or Linux. 

* On Linux we need to ensure that the directory containing our stata/stata-mp binary is on PATH

```bash
# export PATH=$PATH:/usr/local/stata18
```

* We need to ensure that our Python installation will be able to find the pystata package. We can do this by defining the `PYTHONPATH` environment variable.

```bash
# Required so nbstata can find pystata package
export PYTHONPATH=/Applications/Stata/utilities
# Linux: export PYTHONPATH=/usr/local/stata18/utilities
# Windows: export PYTHONPATH="C:/Program Files/Stata18/utilities"
```

* We then setup the virtual environment. This will create a directory in our project called _.venv_. I prefer to explicitly set the version of Python I am using.

```bash
uv venv --python 3.13
```

* We then activate the virtual environment

```bash
source .venv/bin/activate
# Windows: source .venv/Scripts/activate
```

* Now we can install the required Python dependency packages.

```bash
# Instal nbstata dependency Python packages
uv pip install jupyterlab nbstata jupyterlab_stata_highlight2

# Additional Python packages if using parameterised Quarto documents
# uv pip install papermill python-dotenv jupyter-cache
```

* Then we setup the nbstata Jupyter kernel

```bash
python -m nbstata.install
```

The nbstata docs states that the --sys-prefix flag may be required in a virutal environment but I haven't found that to be the case.

* Then we issue the commands to do our actual work; for example rendering a Quarto document using the `jupyter: nbstata` engine.

```bash
quarto render index.qmd --execute --execute-daemon-restart
```

* And when you have finished your work you can deactivate the virtual environment

```bash
deactivate
```

## Summary

I have shown how to setup and run the nbstata Jupyter kernel within a uv virtual environment.
