---
title: 'Some tips for working with Quarto revealjs presentations'
author: Package Build
date: '2024-01-20'
slug: quarto-revealjs-tips
categories:
  - Blog
tags:
  - Quarto
  - R
  - revealjs
subtitle: ''
summary: 'Some hopefully helpful tips for working with Quarto revealjs html presentations.'
authors: []
lastmod: '2025-01-20T09:15:00+00:00'
featured: no
image:
  caption: ''
  focal_point: 'Center'
  preview_only: no
  alt_text: 'Screenshot of a Mentimeter presentation embedded in a Quarto revealjs html slide.'
projects: []
---

## Introduction

Like alot of lecturers I'm teaching at the moment. If I have a presentation to do that's mainly images I'll use Powerpoint or Google Slides, and if I have alot of maths or code or both I used to use LaTeX Beamer presentations. Over the years I have grown tired of Beamer and so I thought I'd try making some revealjs presentations using Quarto.

It's important to stress that revealjs has been around far longer than Quarto, I remember seeing a colleague present one in about 2008, and you can happily make a revealjs presentation without Quarto.

The following tips are little hurdles I found I needed to overcome.

## Wider code styling



## Longer code chunks



## Longer code output chunks

## Embedding interactive Mentimeter presentations

## Summary

I have shown a few tips I needed to workout when making revealjs presentations with Quarto.
